# Generated by Django 5.2 on 2025-05-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok',
            field=models.PositiveIntegerField(),
        ),
    ]
