# Generated by Django 5.2 on 2025-05-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='produk',
        ),
    ]
