# Generated by Django 5.2 on 2025-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_remove_transaksi_jumlah_remove_transaksi_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dibayar', 'Dibayar'), ('dikirim', 'Dikirim'), ('selesai', 'Selesai')], default='pending', max_length=20),
        ),
    ]
