# Generated by Django 5.2 on 2025-05-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_rating'),
        ('transaksi', '0003_transaksi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.cart'),
        ),
    ]
