# Generated by Django 5.2 on 2025-05-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0004_transaksi_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='jumlah_terbayar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
